-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE 
FROM (SELECT C.CAR_ID, C.CAR_TYPE, ROUND(
    C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = "30일 이상"
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND NOT EXISTS (
    SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H WHERE 
    C.CAR_ID = H.CAR_ID AND H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-1'
)
) T
WHERE T.FEE >= 500000 AND T.FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC