-- 코드를 작성해주세요
WITH RECURSIVE T1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT T2.ID, T2.PARENT_ID, GENERATION +1 AS GENERATION
    FROM T1 JOIN ECOLI_DATA T2 ON T2.PARENT_ID = T1.ID
)
SELECT COUNT(T1.ID) AS COUNT, T1.GENERATION
FROM T1
WHERE T1.ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION