-- 코드를 입력하세요
SELECT TITLE, GB.BOARD_ID, REPLY_ID, GR.WRITER_ID, GR.CONTENTS, 
DATE_FORMAT(GR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD GB, USED_GOODS_REPLY GR
WHERE GB.BOARD_ID = GR.BOARD_ID AND LEFT(GB.CREATED_DATE, 7) = '2022-10'
ORDER BY GR.CREATED_DATE, TITLE
